In [1]:
from PIL import Image
import numpy as np

import matplotlib.pyplot as plt


In [2]:
def cal_vdvi(image):
    pass




In [12]:

image_path = "../datasets/tianchi_no/image/image_10_256.png"
image = Image.open(image_path).convert("RGB")

# image = np.asarray(image)

In [18]:
# plt.imshow(image[:,:, 2])
# print(image.shape)



def calc_vdvi(image):
    r, g, b = image.split()
    r = np.asarray(r)
    g = np.asarray(g)
    b = np.asarray(b)
    numerator = 2 * g - r - b
    denominator = 2 * g + r + b
    denominator[denominator == 0] = 1
    # 分子
    return numerator / denominator



[[1.8125     0.98347107 0.82312925 ... 0.47368421 0.472      0.44444444]
 [1.16       0.93650794 0.92481203 ... 0.47096774 0.46875    0.46534653]
 [0.77483444 0.68786127 0.70760234 ... 0.51048951 0.50819672 0.44761905]
 ...
 [0.06329114 0.23076923 0.10144928 ... 0.04       0.025      0.00645161]
 [0.10091743 0.48148148 0.07936508 ... 0.025      0.01234568 0.        ]
 [0.09734513 0.04       0.41176471 ... 0.01234568 1.44067797 1.27135678]]
